name: 'movielens_analytics'
version: '1.0.0'

profile: 'movielens_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  movielens_analytics:
    example:
      +materialized: view

seeds:
  movielens_analytics:
    +schema: raw

    movies:
      +quote_columns: false
      +column_types:
        movieId: integer
        title: varchar
        genres: varchar